spring.config.import=optional:application-local.properties

spring.application.name=findit-backend

spring.datasource.url=jdbc:mysql://localhost:3306/findit_db
spring.datasource.username=root
spring.datasource.password=spring.datasource.password=${DB_PASSWORD:changeme}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret=findit-super-secret-key-change-this-in-production-1234567890

spring.jackson.serialization-inclusion=NON_NULL
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss